INPUT_VALIDATOR_ATTR_NAME = "__VERCAJK_INPUT_VALIDATOR"
INPUT_VALIDATOR_GQL_NAME = "__VERCAJK_INPUT_VALIDATOR_GQL_NAME"
INPUT_IS_PARTIAL = "__VERCAJK_INPUT_IS_PARTIAL"
INPUT_PROVIDED_FIELD_NAMES = "__VERCAJK_INPUT_PROVIDED_FIELD_NAMES"
